### ISSUE TITLE
Comparison to Temporal

### ISSUE THREAD

**Issue by elovelan** [DidactHQ/didact-docs#5]
This seems to scratch similar itches to [Temporal](https://temporal.io/). I very much appreciated your Hangfire comparison. Would you be willing to do a similar one for Temporal? My company is actively investigating code-based workflow solutions.

**Comment by DMiradakis** [comment]
Hi @elovelan , my apologies for getting to this so late, I never saw the notification appear and have been extremely busy getting Didact v1 ready! Yes, absolutely, I would be happy to write a comparison page about them - I've actually already started researching our similarities and differences a few weeks ago. 😄 I will leave this issue open for now and will let you know when the comparison page is written.

By the way, did your company ever make a choice on the solution?

**Comment by elovelan** [comment]
no, we're still stuck on AWS Step Functions, which despite having _some_ code abstractions via the CDK, is much less than ideal given its JSON-based implementation!

**Comment by DMiradakis** [comment]
Hey @elovelan, I've actually been doing some research and soul-searching for what makes Didact different from something like Temporal, and I think I've got some really good answers. I'll comment back today or tomorrow and let you know what those answers are, I think they will really help clarify the difference in use cases.

**Comment by DMiradakis** [comment]
Hi @elovelan , my apologies for taking a while to respond to this, been feeling a little under the weather. I still want to write a proper blog posting/comparison page on Temporal.io vs. Didact, but I've got a few good points to start with that I think really hit the nail on the head for the most important factors!

Distributed Systems and Microservices

- Temporal seems primarily built for **massive distributed systems**. It can be run as a single node or in a monolith, sure, but neither of those use cases really fit the intent (in my opinion) for why Temporal was built. Really large distributed systems seems to be Temporal's primary use case.
- In particular, when I say massive distributed systems, I'm thinking of a **microservice architecture** where you have various microservice pieces of infrastructure all needing to coordinate/communicate with each other.
- You could look at it as an alternative to something like .NET Orleans, for example, but it has more opinionated design choices on workflow execution, specifically, and tailoring specifically to that frame of thinking. For example, Temporal has a nice UI dashboard to visualize the workflow executions whereas Orleans doesn't really have something like this.

Long-lived, Out-of-Process, Distributed Transactions

- Temporal also seems to pride itself on being able to execute long-lived, out-of-process, distributed transactions.
- When I say long-lived and out-of-process, I'm talking about distributed transactions that are broken down into individual pieces (called Activities in their framework) that are atomically executed piece by piece, where metadata is sent and updated at the database layer per atomic execution, and then the workflow is queued/triggered at some point later (maybe immediately, maybe months from now) to execute the next atomic step.
- Basically, think of Temporal workflows as chunks of atomic code that need to execute as steps, and every execution step has to interact with the database layer before and after executing and possible wait for some sort of long duration. So, for example, if you needed to wait 1 month to send an email, you would NOT want to consume a C# thread/task for one month straight (due to server resources, shutdowns, blocked threads, etc.). Instead, you would want to "put to sleep" your workflow and "wake it up" in a month without consuming server resources in the in-between waiting time. Hence the long-lived and out-of-process descriptors.
- And again, since Temporal is designed for massive distributed systems and architectures, these characteristics are a part of what I would call overall distributed transactions.

So basically Temporal can help you deal with making all of your microservices talk to each in a prebuilt/opinionated workflow sort of fashion.

Here's some of the differences it has with Didact:

- Think of Didact as being the queuing system and workflow execution for each little microservice. Didact doesn't really focus on coordinating chunks of work across microservices, rather, it focuses on efficiently and intelligently executing work for each little microservice.
- Better yet, if you don't even use microservices, I am very confident that Didact is much better fit for you.
- Didact is more focused on workflows that are in-process where you want to execute a chunk of work in one fell swoop. `DoSomething()`... `DoSomethingElse1()`... `DoSomethingElse2()` and so on.
- I absolutely have the ability to offer constructs in Didact to support distributed transactions, but honestly that's not what I'm really focused on right now.
- Didact is supposed to provide you an extremely convenient plug-n-play system for defining "Flows" (your workflows) and executing them efficiently and at scale. The Flows are not necessarily supposed to span weeks or months at a time, but rather execute in fell swoops.

I actually use ChatGPT to organize a lot of my architectural thoughts for Didact, and I thought this little excerpt was pretty helpful actually:

Key Differentiator: Temporal Workflow vs Didact FlowRun

Temporal Workflow:
- Designed to orchestrate and manage state over time, interacting with multiple services.
- It has "memory" and durability, with replays and deterministic execution for long-term reliability.

Didact FlowRun:
- Designed for efficient, bounded execution of jobs.
- It’s leaner and simpler, focusing on short-lived async operations, with resilience provided through retries and task scheduling rather than long-term state persistence.

Choosing Between Temporal and Didact

- Choose Temporal if you need to orchestrate long-running workflows across microservices, with strong state guarantees and persistence across failures.
- Choose Didact if you need a lightweight orchestrator to handle transactional jobs or asynchronous workflows, particularly in monoliths or basic distributed systems where simplicity and performance matter most.

Does that help?

**Comment by DMiradakis** [comment]
Whew... I actually spent like 3 days writing a huge comparison article. I'm still wrapping up v1 of Didact, but I figured I could go ahead and write this in the meantime: https://www.didact.dev/compare/didact-vs-temporal

By the way, is your company still looking around for solutions? Would love to have to try Didact here in about a month and half or so! @elovelan

**Comment by elovelan** [comment]
We're actually just about to look into some perf improvements and it's pretty high on the list of options. We're an AWS shop and I want to avoid step functions

**Comment by DMiradakis** [comment]
Awesome! If you haven't submitted your email to the site, please do so or just email me at daniel@didact.dev so we can stay in touch! I'm going to send some newsletters out again any day now, would absolutely love to have you and your company.

Thanks for the suggestion for this article, I'm going to go ahead and close this issue.

**Comment by elovelan** [comment]
Just want to say @DMiradakis, I finally got a chance to read through that comparison on the site and it is excellent! Well done! 💯
